


# VAR1 = helloworld
# VAR1 = x01convertMilesToKms
# VAR1 = x02CLIarguments1
VAR1 = x02CLIarguments2











VAR2 = outputBinaryFile

wow: $(VAR1).c
	gcc $(VAR1).c -o $(VAR2)
	# sleep 1
	# echo " "
	clear
	./$(VAR2)

clear:
	rm $(VAR2)